import type { ImproveCategory } from '@/types/improve';

export const IMPROVE_CATEGORIES: ImproveCategory[] = [
  {
    id: 'physical',
    title: 'Physical',
    description: 'Speed, power, and athleticism on the pitch',
    icon: 'fitness-outline',
    skills: [
      {
        id: 'speed',
        title: 'Speed',
        summary: 'Accelerate faster and reach top speed in fewer steps.',
        explanation:
          'Speed in football is rarely about running in a straight line for 100m. It is about how quickly you can reach a high velocity over 5–20 metres — to beat a press, chase a through ball, or recover defensively. Train acceleration and max velocity separately, and always finish drills with a ball or game-like cue so the speed transfers to match situations.',
        drills: [
          {
            id: 'acceleration-sprints',
            title: '10m Acceleration Sprints',
            equipment: ['Cones', 'Stopwatch (optional)'],
            duration: '6 reps, full recovery between each',
            requiresPartner: 'solo',
            steps: [
              'Mark a 10m line on flat ground with cones.',
              'Start from a standing or three-point stance behind the line.',
              'Sprint through the 10m zone with a low, powerful drive phase for the first 3 steps.',
              'Walk back to the start and fully recover before the next rep.',
              'Complete 6 reps, focusing on explosive first steps each time.',
            ],
            coachingCues: [],
            commonMistakes: [],
          },
          {
            id: 'flying-sprints',
            title: 'Flying 20m Sprints',
            equipment: ['Cones', 'Stopwatch (optional)'],
            duration: '4–6 reps, full recovery; repeat weekly',
            requiresPartner: 'solo',
            steps: [
              'Set up a 15m build-up zone and a 20m flying sprint zone (35m total).',
              'Jog or stride through the build-up zone to reach near top speed.',
              'Sprint at maximum effort through the full 20m flying zone.',
              'Record your best time if using a stopwatch.',
              'Walk back and fully recover before the next rep.',
            ],
            coachingCues: [],
            commonMistakes: [],
          },
          {
            id: 'ball-at-feet-sprint',
            title: 'Ball at Feet Sprint',
            equipment: ['Ball', 'Cones'],
            duration: '6–8 reps, moderate recovery',
            requiresPartner: 'solo',
            steps: [
              'Place a cone 15m from the start line with a ball at your feet.',
              'Dribble at controlled pace for 15m.',
              'As you pass the cone, explode into a 10m sprint — push the ball ahead in short touches.',
              'Decelerate safely after the sprint zone.',
              'Reset and repeat, mimicking receiving and breaking away in a match.',
            ],
            coachingCues: [],
            commonMistakes: [],
          },
        ],
      },
      {
        id: 'agility',
        title: 'Agility',
        summary: 'Change direction quickly while staying balanced.',
        explanation: '',
        drills: [],
      },
      {
        id: 'stamina',
        title: 'Stamina',
        summary: '',
        explanation: '',
        drills: [],
      },
      {
        id: 'strength',
        title: 'Strength',
        summary: '',
        explanation: '',
        drills: [],
      },
    ],
  },
  {
    id: 'technical',
    title: 'Technical',
    description: 'Ball mastery and execution under pressure',
    icon: 'football-outline',
    skills: [
      {
        id: 'first-touch',
        title: 'First touch',
        summary: 'Control the ball into space on your first contact.',
        explanation:
          'Your first touch sets up everything that follows — the pass, shot, or dribble. A good touch moves the ball away from pressure and into your next action. The direction and weight of your touch matter more than soft feet alone.',
        drills: [
          {
            id: 'box-passing-pattern',
            title: 'Box Passing Pattern',
            equipment: ['4 cones', 'Ball', 'A partner'],
            duration: '8–10 minutes',
            requiresPartner: 'partner',
            videoUrl: 'https://youtu.be/VqOnafc-Ufs?si=jFgz4o6Mi2WHEgR3',
            videoTimestamp: '0:19',
            videoTimestampSeconds: 19,
            steps: [
              'Set up a small square using 4 cones, roughly 5x5 yards, with a partner standing at the opposite corner.',
              'Your partner passes the ball to you along one side of the square.',
              'Take one touch with the inside of your foot to redirect the ball at an angle — turning it to travel along the next side of the square, not straight back.',
              'Pass the ball onward using the inside of your foot, at 5–10 yards, timed so your partner can control it in one movement.',
              'After a few reps, switch to one-touch passing only — receive and immediately redirect in the same motion, no separate controlling touch.',
              'Rotate which foot leads: use the inside of your foot when turning the ball across your body, and the outside of your foot when opening up away from your body.',
              'Keep the ball on the ground for the entire pattern — the drill is about clean technique, not power.',
            ],
            coachingCues: [
              'Ball stays on the ground with minimal bobble on the touch.',
              'Pass weight should let your partner control it in one movement, not chase it down.',
            ],
            commonMistakes: [
              'Touch is too heavy and pushes the ball out of the square.',
              'Passing too hard for the distance, turning it into a fight to control rather than a smooth pattern.',
            ],
          },
          {
            id: 'tight-trap',
            title: 'Tight Trap (Killing the Ball)',
            equipment: ['4 cones', 'Ball', 'A partner'],
            duration: '5–8 minutes',
            requiresPartner: 'partner',
            videoUrl: 'https://youtu.be/VqOnafc-Ufs?si=jFgz4o6Mi2WHEgR3',
            videoTimestamp: '1:19',
            videoTimestampSeconds: 79,
            steps: [
              'Mark out a small 2x2 or 3x3 yard square using cones.',
              'Stand inside the square while your partner stands outside it.',
              'Partner fires the ball at you on the ground or below knee height, at real pace — this should not be an easy feed.',
              'Your job is to kill the ball dead inside the square using your first touch.',
              'Once the ball is fully under control, decide your next action (pass back, turn, etc.).',
              'Repeat continuously, resetting your position each time.',
            ],
            coachingCues: [
              'The touch should stop the ball almost completely, with no follow-through roll.',
              'A good rep means you can immediately lift your head after the touch, not chase the ball first.',
            ],
            commonMistakes: [
              'Ball bounces away from your feet on contact instead of dying under control.',
              'Rushing the next action before the ball is actually settled.',
            ],
          },
          {
            id: 'touch-into-space',
            title: 'Touch Into Space',
            equipment: ['Cones (optional)', 'Ball', 'A partner'],
            duration: '8–10 minutes',
            requiresPartner: 'partner',
            videoUrl: 'https://youtu.be/VqOnafc-Ufs?si=jFgz4o6Mi2WHEgR3',
            videoTimestamp: '2:31',
            videoTimestampSeconds: 151,
            steps: [
              'Partner passes the ball to you from a short distance away.',
              'Instead of killing the ball dead, take your first touch out in front of you into open space.',
              'Immediately accelerate onto the ball at speed after the touch.',
              'Vary the touch: inside foot, outside foot, left foot, right foot, and try a Cruyff turn version too.',
              'Make it position-specific — practice receiving and touching into the space you would realistically get on the pitch in your position.',
            ],
            coachingCues: [
              'The touch should be firm enough that you have to chase onto the ball, not just walk onto it.',
              'First two steps after the touch should be explosive.',
            ],
            commonMistakes: [
              'Touch is too soft and the ball barely moves, defeating the purpose of the drill.',
              'Standing upright immediately after the touch instead of bursting into the space.',
            ],
          },
          {
            id: 'receiving-the-long-pass',
            title: 'Receiving the Long Pass',
            equipment: ['Ball', 'A partner 20–40 yards away'],
            duration: '8–10 minutes',
            requiresPartner: 'partner',
            videoUrl: 'https://youtu.be/VqOnafc-Ufs?si=jFgz4o6Mi2WHEgR3',
            videoTimestamp: '3:29',
            videoTimestampSeconds: 209,
            steps: [
              'Partner stands 20–40 yards away and drives or lofts a long pass to you.',
              'Receive the ball and take your touch based on your position on the pitch.',
              'Example: a fullback might take it down the line and accelerate past; a striker might hold up play; a center-mid might take it into the pocket; a center-back might cushion a long ball from the keeper.',
              'Make the drill specific to your position and where you would realistically receive this pass in a match.',
              'Repeat, alternating the angle and pace of the incoming pass.',
            ],
            coachingCues: [
              'First touch direction should immediately set up your next action — accelerate, turn, or shield — not just control for its own sake.',
            ],
            commonMistakes: [
              'Taking a "safe" touch that does not progress play, forcing an unnecessary second touch.',
            ],
          },
          {
            id: 'square-battle-2v2',
            title: '2v2 Square Battle',
            equipment: ['Cones (2 adjacent squares)', 'Ball', '3 other players (or 1 for a 1v1 version)'],
            duration: 'Play to 7 or 11 points',
            requiresPartner: 'group',
            videoUrl: 'https://youtu.be/VqOnafc-Ufs?si=jFgz4o6Mi2WHEgR3',
            videoTimestamp: '4:21',
            videoTimestampSeconds: 261,
            steps: [
              'Set up two adjacent squares using cones. Split into two teams of two players each (or 1v1 for a simpler version).',
              'Hit the ball into the opposite square, keeping it below knee height.',
              'Whoever receives the ball must take a touch to kill it for their partner.',
              'Their partner then plays the ball into the opposite square.',
              'If your touch escapes the square, or your team cannot return the ball into the opposite square, the other team scores a point.',
              'Play continuously to 7 or 11 points.',
            ],
            coachingCues: [
              'Success means staying composed and able to combine with your partner even under constant pressure from difficult, low, fast-arriving balls.',
            ],
            commonMistakes: [
              'Rushing the touch under pressure and losing control entirely, rather than staying composed.',
            ],
          },
          {
            id: 'three-touch-juggles',
            title: 'Three Touch Juggles',
            equipment: ['Football', 'A wall'],
            duration: '5 minutes',
            requiresPartner: 'solo',
            videoUrl: 'https://youtu.be/ON8mSEeXI8o?si=N8IX9UJq9tyZkJEp',
            videoTimestamp: '0:39',
            videoTimestampSeconds: 39,
            steps: [
              'Volley the ball against the wall.',
              'You have a maximum of three touches to get the ball under control and return it to the wall.',
              'Stay light on your feet with a low center of gravity to help you adjust to the flight of the ball.',
              'Use a variety of touches — chest, thighs, and both feet — including the laces, inside, and outside of the foot.',
              'Keep going continuously, resetting your touch count each time the ball returns from the wall.',
            ],
            coachingCues: [
              'Low center of gravity, light on your feet, ready to adjust to unpredictable bounces.',
              'Use every surface — not just your stronger foot.',
            ],
            commonMistakes: [
              'Standing flat-footed and reacting late to the ball.',
              'Only using one foot or surface out of habit.',
            ],
          },
          {
            id: 'two-touch-juggles',
            title: 'Two Touch Juggles',
            equipment: ['Football', 'A wall'],
            duration: '5 minutes',
            requiresPartner: 'solo',
            videoUrl: 'https://youtu.be/ON8mSEeXI8o?si=N8IX9UJq9tyZkJEp',
            videoTimestamp: '1:59',
            videoTimestampSeconds: 119,
            steps: [
              'Volley the ball against the wall.',
              'You have a maximum of two touches — one to control the ball, one to play it back to the wall.',
              'Since there is no extra touch to fix a bad first touch, focus on making that first contact clean.',
              'Stay light on your feet with good balance, using all surfaces of the body — chest, thighs, both feet.',
              'Vary your pattern: sometimes control and return with the same foot, sometimes take the touch across your body and return with the opposite foot.',
            ],
            coachingCues: [
              'First touch must be clean and controlled — there is no third touch to correct a mistake.',
              'Mix same-foot and cross-body patterns rather than always repeating one pattern.',
            ],
            commonMistakes: [
              'Rushing the first touch, leaving a poor angle for the return pass to the wall.',
              'Only practicing one foot/pattern instead of varying it.',
            ],
          },
          {
            id: 'one-touch-juggles',
            title: 'One Touch Juggles',
            equipment: ['Football', 'A wall'],
            duration: '5 minutes',
            requiresPartner: 'solo',
            videoUrl: 'https://youtu.be/ON8mSEeXI8o?si=N8IX9UJq9tyZkJEp',
            videoTimestamp: '3:09',
            videoTimestampSeconds: 189,
            steps: [
              'Using feet only, return the ball to the wall in a single touch every time — no controlling touch allowed.',
              'Stay light on your feet since there is no second touch to recover from a poor connection.',
              'Use both feet and all surfaces — outside, laces, and inside of the foot.',
              'Keep your focus on the ball at all times, aiming for a clean connection that sends it back at the wall.',
              'Try to keep the sequence going for as long as possible without losing control.',
            ],
            coachingCues: [
              'Balance and focus matter most here — no second touch to fall back on.',
              'Aim for a clean, controlled connection rather than just making contact.',
            ],
            commonMistakes: [
              'Losing balance on off-footed or awkward-angle touches.',
              'Only using strong-foot laces instead of practicing all surfaces.',
            ],
          },
          {
            id: 'single-side-juggles',
            title: 'Single Side Juggles',
            equipment: ['Football', 'A wall'],
            duration: '5 minutes',
            requiresPartner: 'solo',
            videoUrl: 'https://youtu.be/ON8mSEeXI8o?si=N8IX9UJq9tyZkJEp',
            videoTimestamp: '4:07',
            videoTimestampSeconds: 247,
            steps: [
              'Volley the ball against the wall, allowed two touches — one to control, one to return.',
              'Both touches must be on the same side of the body — e.g. if your first touch is with your right foot, your return pass must also be with your right foot.',
              'If your first touch is with your left thigh, your return must be with your left foot.',
              'Focus on adjusting your body position so the same-side return is accurate.',
              'See how long you can keep the sequence going.',
            ],
            coachingCues: [
              'This drill is about accurate positioning — adjust your body early to set up the same-side return.',
            ],
            commonMistakes: [
              'Defaulting to the stronger foot for the return, breaking the same-side rule.',
              'Poor body adjustment leading to a rushed, inaccurate return touch.',
            ],
          },
          {
            id: 'alternating-side-juggles',
            title: 'Alternating Side Juggles',
            equipment: ['Football', 'A wall'],
            duration: '5 minutes',
            requiresPartner: 'solo',
            videoUrl: 'https://youtu.be/ON8mSEeXI8o?si=N8IX9UJq9tyZkJEp',
            videoTimestamp: '5:20',
            videoTimestampSeconds: 320,
            steps: [
              'Volley the ball against the wall, allowed two touches — one to control, one to return.',
              'This time, the return touch must be on the opposite side from the controlling touch.',
              'Example: if you control with your right foot, you must play it back with your left foot. If you control with your left thigh, return with your right foot.',
              'Focus on accurately bringing the ball across your body before the return touch.',
              'Use as many different surfaces as possible — both thighs and both feet — and see how long you can keep it going without dropping the ball.',
            ],
            coachingCues: [
              'The first touch needs to bring the ball across your body accurately to set up the opposite-foot return.',
            ],
            commonMistakes: [
              'Cross-body touch is too heavy, making the opposite-foot return impossible to control.',
            ],
          },
        ],
      },
      {
        id: 'passing',
        title: 'Passing',
        summary: '',
        explanation: '',
        drills: [],
      },
      {
        id: 'shooting',
        title: 'Shooting',
        summary: '',
        explanation: '',
        drills: [],
      },
    ],
  },
  {
    id: 'tactical',
    title: 'Tactical',
    description: 'Reading the game and making smart choices',
    icon: 'grid-outline',
    skills: [
      {
        id: 'positioning',
        title: 'Positioning',
        summary: '',
        explanation: '',
        drills: [],
      },
      {
        id: 'decision-making',
        title: 'Decision making',
        summary: '',
        explanation: '',
        drills: [],
      },
    ],
  },
  {
    id: 'mental',
    title: 'Mental',
    description: 'Focus, confidence, and composure',
    icon: 'bulb-outline',
    skills: [
      {
        id: 'composure',
        title: 'Composure',
        summary: '',
        explanation: '',
        drills: [],
      },
      {
        id: 'confidence',
        title: 'Confidence',
        summary: '',
        explanation: '',
        drills: [],
      },
    ],
  },
];
